# railway.toml

[project]
name = "Search Chats"

# Define a single service array
[[services]]
name = "api-service"
root_directory = "api/v1"
  
# Environment variables for this service
[services.env]
NODE_ENV = "production"
PORT = "3000"  # Replace with the port Railway uses or your application's port
  
# Build and deploy commands
[services.build]
build_command = "npm install && npm run build"
  
[services.deploy]
start_command = "npm run dev"
