[project]
name = "Search Chats"

[services]
  [[services]]
  name = "api-service"
  # Set the root directory to `api/v1`
  root_directory = "api/v1"
  
  [services.env]
  # Add environment variables here, e.g.
  NODE_ENV = "production"
  PORT = "3000"  # Port that Railway should expose

  [services.build]
  # Commands to build your backend code if required (e.g., transpile or setup)
  build_command = "npm install && npm run build"
  
  [services.deploy]
  # Command to start your backend service
  start_command = "npm start"  # or replace with `npm run dev` if appropriate
